# bundle exec jekyll serve --host=0.0.0.0

title: StreamDebugger
description: StreamDebugger allows easier debugging of Serial-based communication on Arduino, like AT commands
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
